name: Build and Push Docker Image to ECR (Production)

on:
  push:
    branches:
      - master   # ONLY trigger when changes reach master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1  # Specify your AWS region

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/automated-triage-app:latest .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/automated-triage-app:latest
